# Generated by Django 6.0.4 on 2026-04-26 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualifiedPositions', models.CharField(max_length=100)),
                ('mlbTeam', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SlfblTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('points', models.IntegerField()),
                ('gameId', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slfbl_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('seasonYear', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slfbl_app.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='slfblTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slfbl_app.slfblteam'),
        ),
        migrations.CreateModel(
            name='WeeklyPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('weekStartDate', models.DateField()),
                ('weekEndDate', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slfbl_app.player')),
            ],
        ),
    ]
