# Generated by Django 6.0.4 on 2026-04-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slfbl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slfblteam',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
