# Generated by Django 6.0.4 on 2026-04-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slfbl_app', '0002_alter_slfblteam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playerId',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
