# Generated by Django 6.0.4 on 2026-04-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slfbl_app', '0003_player_playerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplayerstats',
            name='gameId',
            field=models.CharField(max_length=100),
        ),
    ]
