# Generated by Django 6.0.4 on 2026-05-10 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slfbl_app', '0004_alter_dailyplayerstats_gameid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'temp_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyPlayerStatForDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerId', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('points', models.CharField(max_length=100)),
                ('totalPoints', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='slfblTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slfbl_app.slfblteam'),
        ),
    ]
