# Generated by Django 6.0.4 on 2026-05-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slfbl_app', '0005_tempdate_dailyplayerstatfordates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name_normalized',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
