# Generated by Django 6.0.4 on 2026-05-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slfbl_app', '0006_player_name_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='slfblteam',
            name='name_normalized',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
