# Generated by Django 6.0.4 on 2026-05-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slfbl_app', '0007_slfblteam_name_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='positionsPlayed',
            field=models.JSONField(default=dict),
        ),
    ]
